# Generated by Django 5.0.3 on 2024-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
