# Generated by Django 5.0.3 on 2024-03-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_productdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
